version: '3.8'

services:
  # -----------------------------------------------------------------
  # BANCO DE DADOS PRINCIPAL (PostgreSQL)
  # -----------------------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: openrewards-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openrewards_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openrewards-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d openrewards_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -----------------------------------------------------------------
  # INTERFACE VISUAL DO BANCO (PgAdmin)
  # -----------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: openrewards-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@openrewards.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - openrewards-network
  redis:
    image: redis:alpine
    container_name: openrewards-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - openrewards-network

    # -----------------------------------------------------------------
    # MENSAGERIA (RabbitMQ com Painel de Gerenciamento)
    # -----------------------------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: openrewards-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Porta do protocolo AMQP
      - "15672:15672" # Porta da Interface Web
    networks:
      - openrewards-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: openrewards-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      # O Prometheus precisa desse arquivo para saber quem monitorar!
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - openrewards-network
    # -----------------------------------------------------------------
    # GRAFANA
    # -----------------------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: openrewards-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - openrewards-network

volumes:
  postgres_data:

networks:
  openrewards-network:
    driver: bridge